name: mojom_standalone
version: 0.0.1
description: A standalone version of the Mojom compiler.
author: Dart Team <misc@dartlang.org>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
